### ISSUE TITLE
登录时, 调用api接口失败? 

### ISSUE THREAD

**Issue by cy-default** [newteo/clockInOut#1]
![image](https://cloud.githubusercontent.com/assets/7159471/23597656/a31ded6a-026f-11e7-8278-814ba7f8610c.png)

**Comment by wardenger** [comment]
试试把“开发环境下不校验请求域名以及TLS版本”勾选上。
by the way, who is this ?

**Comment by cy-default** [comment]
![image](https://cloud.githubusercontent.com/assets/7159471/23599687/7f52a516-027d-11e7-8880-c3958a70538a.png)  那个我已经勾选上了. 还是把这个错误.

**Comment by wardenger** [comment]
你没有我们这个小程序的appId，所以会报错。

**Comment by cy-default** [comment]
好吧, 那朋友 能提供个下样例截图给看下么? 我QQ704906706
