### ISSUE TITLE
 module "secret.js" is not defined 

### ISSUE THREAD

**Issue by laonayan** [newteo/clockInOut#2]
sdk uncaught third Error 
 module "secret.js" is not defined 
 Error: module "secret.js" is not defined

![_20180503135645](https://user-images.githubusercontent.com/32827448/39561699-f6ae5d4a-4ed9-11e8-8a4e-ab66c6ef3f3b.png)

**Comment by joephon** [comment]
@HuaiAnGG 
That file is an env file~ 
which was ignored by .gitignore file
use your personal key instead~

**Comment by jojoZhq** [comment]
请问如何获取personal key？刚入门，不太懂

**Comment by joephon** [comment]
@jojoZhq  这个文件是秘钥文件 不公开的
